version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.49.0
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Use nightly rust
          command: rustup default nightly
      - run:
          name: Add riscv32imac-unknown-none-elf rust target
          command: rustup target add riscv32imac-unknown-none-elf
      - run:
          name: Build
          command: cargo build --verbose
      - run:
          name: Build bootloader
          command: cd bootloader && cargo build --verbose

workflows:
  version: 2.1

  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
